### PR TITLE
feat: add labels for each star

### PR DESCRIPTION
**Pull request by kurucaner**

### CODE REVIEW

**Comment by kurucaner** [comment]
I needed this feature for an app I'm developing and thought it could be a valuable contribution. Please let me know what you think.

**Comment by bviebahn** [comment]
Thanks for your contribution! I think it would be a little more flexible if we used the `StarIconComponent` prop to add labels. This way you could for example also put the labels at the top or change the label style based on if the star is filled or not. Something like this:
```ts
import StarRating, {
  StarIcon,
  StarIconProps,
} from 'react-native-star-rating-widget';

const labels = ['Terrible', 'Bad', 'Okay', 'Good', 'Great'];

const LabelIcon = (props: StarIconProps) => {
  return (
    <View style={styles.iconContainer}>
      <StarIcon {...props} />
      <Text>{labels[props.index]}</Text>
    </View>
  );
};

const LabelExample = () => {
  const [rating, setRating] = React.useState(2.5);

  return (
    <StarRating
      rating={rating}
      onChange={setRating}
      StarIconComponent={LabelIcon}
    />
  );
};
```
We would have to add the index to the StarIconComponent prop. What do you think?

**Comment by kurucaner** [comment]
It makes sense. So in this case we need to pass index as a prop to StarIconComponent right? Because the current StarIconProps are size, color and type.

**Comment by bviebahn** [comment]
Great, looks good! I created a new release. Thanks for your help!

**Comment by kurucaner** [comment]
Glad I was able to contribute somehow.

**Pull request merged**
